apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurail-app
  namespace: eurail-zoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurail-app
  template:
    metadata:
      labels:
        app: eurail-app
    spec:
      containers:
      - name: app
        image: eurail-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/eurail_db
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
        - name: SPRING_FLYWAY_VALIDATE_ON_MIGRATE
          value: "false"
        - name: SPRING_FLYWAY_REPAIR_ON_MIGRATE
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: eurail-app
  namespace: eurail-zoo
spec:
  selector:
    app: eurail-app
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort

